### ISSUE TITLE
User Dashboard does not show all entries - Private instance

### ISSUE THREAD

**Issue by mtchetch** [pglombardo/PasswordPusher#444] opened 2022-10-25 15:50 UTC
Checked the dashboard and the passwords database table. Dashboard does not show all pushed passwords.

Expected result:

Dashboard shows all non expired pushes

Results I got:

Dashboard shows 30 entries. The rest do not show but are in the database and are usable.

**Comment by pglombardo** [comment] 2022-10-25 16:35
Hey @mtchetch - good to hear from you again.

Could those pushes be in the `expired` tab?

If not and you agree, could you create a new push with:

1.  a few of the URL IDs? (the secret token in `/p/[secret-token]`.
2. your login email

You can send me the push URL via the [feedback form](https://pwpush.com/en/feedbacks/new) or directly to my email pglombardo at hey.com

I won't open the URLS but I will look into the database to see if I can find what the issue is.

**Comment by mtchetch** [comment] 2022-10-25 16:59
Using a private instance. The pushes are not in the expired tab. The main listing seems to be limited to 30 entries but the database has more non expired entries for that user ID.

**Comment by pglombardo** [comment] 2022-10-25 19:04
That page has pagination built in - there should be nav element at the bottom of the page:

![Screenshot 2022-10-25 at 21 03 08](https://user-images.githubusercontent.com/395132/197859876-8ef0dc65-80f5-44ac-8799-c4c2e00df7dd.png)

(Dark mode since it's late here)

Try this URL on your private instance: `/en/d/active?page=2`  If there is a 2nd page, that path will show it.

**Comment by mtchetch** [comment] 2022-10-26 14:55
> That page has pagination built in - there should be nav element at the bottom of the page:
> 
> ![Screenshot 2022-10-25 at 21 03 08](https://user-images.githubusercontent.com/395132/197859876-8ef0dc65-80f5-44ac-8799-c4c2e00df7dd.png)
> 
> (Dark mode since it's late here)
> 
> Try this URL on your private instance: `/en/d/active?page=2` If there is a 2nd page, that path will show it.

Tried updating the image (pglombardo/pwpush-mysql:latest)  and Firefox and Edge browsers. Both browsers do not show the pagination controls, but work with the ?page= url parameter and do show the next 30 entries when changing the page manually thwough the url parameter. Also checked dev console for error messages and no errors are visible.

![image](https://user-images.githubusercontent.com/11362763/198060300-686849b7-1f82-4cbc-811b-7e81bb2580d9.png)

**Comment by pglombardo** [comment] 2022-10-26 15:13
I think I found the bug...  Let me test and release a new container.

**Comment by pglombardo** [comment] 2022-10-26 15:31
The fix is tested and merged.  A container tag `v1.17.12` is [being built now](https://github.com/pglombardo/PasswordPusher/actions/runs/3330383271).  It usually takes about ~30 mins.

Once it's ready, could you try that tag and confirm that the pagination controls show up now?

**Comment by mtchetch** [comment] 2022-10-27 08:41
Tested working on my system. Good job!

**Comment by pglombardo** [comment] 2022-10-27 09:06
That's great to hear - thanks for pointing this out!

**Closed by pglombardo** 2022-10-27 09:06 UTC
Labels: bug moderate
