### ISSUE TITLE
Unable to read push files

### ISSUE THREAD

**Issue by Abhishek0237** [pglombardo/PasswordPusher#2385] opened 2024-07-31 21:16 UTC
Hey!
I hope you are doing well!

We have just enabled file pushes and are using local storage for uploads. We have mapped the drive on a Windows computer using Samba but whenever the client uploads the files. It doesn't show any file extensions. We cannot determine which kind of file clients uploaded like it  excel,png or any other file.

Please find the below screenshot

![issue](https://github.com/user-attachments/assets/9d2b2c4c-fcf3-4b6c-b9fd-ae5d6f0446e2)

**Comment by pglombardo** [comment] 2024-07-31 21:24
Hi @Abhishek0237 - that is by design.  What is the use case?  Why would you need to see the files?

**Comment by Abhishek0237** [comment] 2024-07-31 21:33
The thing is suppose the client takes  the screenshot of any information  and sent us as an image(png) file instead of properly write in the world or notepad file. How we can know at first seen either it is just image file or it's proper document. because we don't want to bother the client again and again.

I know we can open files with the browser to see the content but I think it's not practical

**Comment by pglombardo** [comment] 2024-07-31 21:43
Ah ok - yeah that is outside the use case for Password Pusher.  By design files are obscured for security.  Currently, the only way is to view the push and download the files locally.

Of course, you could automate this with the [JSON API](https://docs.pwpush.com/docs/json-api/) to automatically download files and place them somewhere on the samba drive...

**Comment by Abhishek0237** [comment] 2024-07-31 21:46
Is Admin can see the file on Secret Portal?

**Comment by pglombardo** [comment] 2024-07-31 22:23
Unfortunately no.  

> How we can know at first seen either it is just image file or it's proper document. because we don't want to bother the client again and again.

I don't understand why you would need to bother the client again and again.  You view the push, and it tells you what type of file it is and shows the file name.  From there you can download the files.  Am I missing something?

**Comment by Abhishek0237** [comment] 2024-07-31 22:30
on local storage, it's not showing what type of file it is that's why i', asking

**Comment by Abhishek0237** [comment] 2024-08-01 16:33
One thing more @pglombardo Can we increase file size for file pushes and what is the default size?

**Comment by Abhishek0237** [comment] 2024-08-01 17:03
no worries I have adjusted nginx for file size

**Comment by Abhishek0237** [comment] 2024-08-01 17:22
One last question I have there Please can we check on "Use a 1-click retrieval step" by default

**Comment by pglombardo** [comment] 2024-08-02 08:07
> One last question I have there Please can we check on "Use a 1-click retrieval step" by default

The docs on setting the default for that option is [here](https://docs.pwpush.com/docs/file-pushes/#configuration).  You can set the environment variable (`PWP__FILES__RETRIEVAL_STEP_DEFAULT=true`) or modify the setting in your [settings.yml](https://docs.pwpush.com/docs/config-strategies/).

**Comment by pglombardo** [comment] 2024-10-06 11:26
Closing.  If anything remains, feel free to open another issue!

**Closed by pglombardo** 2024-10-06 11:26 UTC
Labels: question
