### ISSUE TITLE
Docker on Azure App Service

### ISSUE THREAD

**Issue by stephenmahood** [pglombardo/PasswordPusher#261] opened 2021-11-04 22:37 UTC
Since the move to puma web server running the docker containers on Azure app service doesn't appear to be working. 

Starting the postgres docker container with env WEBSITE_PORTS=5100 and PORT either undefined or 5100 results in the puma webserver starting up on port 5200. This results in the app not being accessible as App Service reverse proxies into the WEBSITE_PORTS port number. 

Running version 1.8.1 on azure app service with WEBSITE_PORTS=5100 works correctly.

**Comment by pglombardo** [comment] 2021-11-08 12:11
Which container are you using?  pwpush-ephemera/postgres/mysql?

**Comment by stephenmahood** [comment] 2021-11-08 14:37
This issue occurs when using the postgres docker image. Microsoft support have confirmed that they are seeing the same issue: 

> I had a chance to look into the image repository and tried to run the same on my end, in order to troubleshoot the cause of the behavior. 
> 
> As I can check, for certain images like 1.10.4 and 1.10.2, when the ‘PORT’ environment variable is being used in the ‘docker run’ command, the application is starting on a Port other than the one which is exposed. This behavior can also be seen while running the image on a local environment. Thus if we try to print the ‘PORT’ environment variable value, it seems to add 100 – to any value passed:
>                $stdout.puts ENV.fetch('PORT')
> 
> It would be suggested to check the cause of the above behavior and if any difference between the 1.8 and 1.10 images are causing such issues – since the 1.8 image works well and starts on the correct port passed.

**Comment by pglombardo** [comment] 2021-11-08 14:48
Yeah I saw your mention of postgres too late :-)  I'm in Azure and will try to reproduce.  I'll post back soon.

**Comment by pglombardo** [comment] 2021-11-08 15:23
I got tripped up on Azure complications  (container networking) but I think I at least identified the problem area.

The entry point for the Docker containers is `entrypoint.sh` which calls `bundle exec foreman start web`.   When I call that directly and set the PORT env var, look what happens:
 
![Screen Shot 2021-11-08 at 16 14 31](https://user-images.githubusercontent.com/395132/140767979-47eb50bd-260d-4ca8-b42a-746ccf0a134c.png)

`foreman` just calls the `Procfile` entry which is `bundle exec puma -C config/puma.rb`.  And that plain commands works without issue:
![Screen Shot 2021-11-08 at 16 14 02](https://user-images.githubusercontent.com/395132/140768192-feb62fd3-f786-4f89-94dd-62e1382c1802.png)

![Screen Shot 2021-11-08 at 16 13 54](https://user-images.githubusercontent.com/395132/140768227-348ec92d-4750-468b-b14a-dd8b18ae0718.png)

So the problem area seems to be the foreman utility.

I'm going to change the entrypoint in the Docker containers to _not_ use foreman which should resolve the issue.  (but probably not today or tomorrow because of appointments)

In the docker CLI, you can override the container entry point.  Could you try overriding the entry point in your Azure instance?

Either way, I'll make this change as soon as I can.  I think it helps in simplicity too.

```
docker run -d -p "5100:5100" --entrypoint "bundle exec puma -C config/puma.rb" pglombardo/pwpush-postgres:1.10.4
```

**Comment by pglombardo** [comment] 2021-11-13 15:39
I merged a fix for this.  Next, I'll build and test containers to confirm and update here.

**Comment by pglombardo** [comment] 2021-11-13 16:41
Tested locally and all seems good.  Could you give docker tag `1.11.1` a try and let me know?

**Comment by stephenmahood** [comment] 2021-11-17 08:54
I've tested out the deployment of 1.11.1 on App Service this morning and it looks to be working correctly now.

**Comment by pglombardo** [comment] 2021-11-17 09:19
Ok that's great to hear.  Thanks for pointing out this issue.

**Closed by pglombardo** 2021-11-17 09:19 UTC
