### ISSUE TITLE
How to Configure HTTPS URL

### ISSUE THREAD

**Issue by dbuehler77** [pglombardo/PasswordPusher#127] opened 2020-03-02 15:24 UTC
![Screen Shot 2020-03-02 at 10 17 24 AM](https://user-images.githubusercontent.com/58781784/75689477-42cbd000-5c6f-11ea-9182-6335f70b8f0c.png)

Notice in the screenshot above that the URL is an http URL. Pwpush is listening over http and I've configured a local nginx proxy to listen on 443 and redirect everything to pwpush's http listener. However, I would like for all URL links (like in the screenshot) to be https URLs.

I don't necessarily need pwpush to actually listen on 443 given I have the nginx proxy, but is it possible to generate the URLs as https URLs?

**Comment by pglombardo** [comment] 2020-03-11 09:37
Hi @dbuehler77 - I believe you can "force SSL" URLs with this setting: https://github.com/pglombardo/PasswordPusher/blob/master/config/environments/production.rb#L9

Could you make sure that `force_ssl` is set to `true` for whichever environment you are running under?  e.g. if `RAILS_ENV=production` then the right config file would be `./config/environments/production.rb`

**Comment by pglombardo** [comment] 2020-03-24 08:54
Hi @dbuehler77 - did this work for you?

**Comment by dbuehler77** [comment] 2020-03-24 13:26
Still having issues. After setting config.force_ssl = true in private.rb (my running env), I'm seeing these errors in my nginx error log:

2020/03/24 13:21:26 [error] 12799#12799: *1 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: X.X.X.X, server: my-pwpush-server.com, request: "GET /favicon.ico HTTP/1.1", upstream: "https://my-pwpush-server.com:5000/favicon.ico", host: "my-pwpush-server.com", referrer: "https://my-pwpush-server.com/"

**Comment by andrew-klassen** [comment] 2020-05-03 22:32
> Still having issues. After setting config.force_ssl = true in private.rb (my running env), I'm seeing these errors in my nginx error log:
> 
> 2020/03/24 13:21:26 [error] 12799#12799: *1 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number) while SSL handshaking to upstream, client: X.X.X.X, server: my-pwpush-server.com, request: "GET /favicon.ico HTTP/1.1", upstream: "https://my-pwpush-server.com:5000/favicon.ico", host: "my-pwpush-server.com", referrer: "https://my-pwpush-server.com/"

I got it working a month or 2 ago and created a saltstate to automate the configuration. 

https://github.com/andrew-klassen/password_pusher

To use it:
1. adjust the "hostname: " varible in vars.yml to your servers hostname that you want presented to the client
2. run the install.sh script 

Below is my nginx config template. I don't remember having to do any special configuration in regards to ssl but I did change my RAILS_ENV to production.

`{% import_yaml 'vars.yml' as vars %}

# Upstreams
upstream backend {
    server 127.0.0.1:5000;
}

# HTTPS Server
server {
    listen 443;
    server_name {{ vars['hostname'] }};

    # You can increase the limit if your need to.
    client_max_body_size 200M;

    error_log /var/log/nginx/rocketchat.access.log;

    ssl on;
    ssl_certificate /etc/nginx/certificate.crt;
    ssl_certificate_key /etc/nginx/certificate.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # don’t use SSLv3 ref: POODLE

    location / {
	proxy_pass http://{{ vars['hostname'] }}:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}`

**Comment by andrew-klassen** [comment] 2020-05-03 22:34
Also the saltstate expect certs to be created and in the correct file paths ahead of time.

**Comment by ant0git** [comment] 2020-05-11 14:34
Hello, I have the same issue. 
I'm running Password Pusher via Docker, i did the change on the line in production.rb, my docker works fine but it doesn't seem to work, it still shows me the http URL.

![image](https://user-images.githubusercontent.com/51849736/81573551-ebe82280-93a4-11ea-9745-8ce140956976.png)

And i'm not sure how to implement the andrew-klassen solution. I have another server for the nginx part, no problem there. Any ideas ?
Thanks

**Comment by pglombardo** [comment] 2020-05-12 07:49
Thanks @andrew-klassen for the helpful info.  @ant0git sorry to hear about the issue.  I'm a bit overloaded currently but I'll see if I can take closer look at this sometime soon.  If anyone from the community can help/chime in - it would be very much appreciated.

**Comment by andrew-klassen** [comment] 2020-05-25 00:29
@pglombardo password pusher is great, but some parts of the installation don't work on modern Linux distros. I have a fairly strong devops background. Would you be interested in me writing a single idempotent shell script that asks the user a couple questions and then automatically installs password pusher with a self signed TLS cert or a cert that the user has provided when running the script?

- the shell script would make use of a configuration management tool called Ansible, Ansible is designed to make deployment of server applications easy to maintain and it works very well with ad-hoc deployments
- this would provide the user with the ability to easily run password pusher on bare-metal, vm, cloud and potentially a container 
- the script would be platform agnostic an work on both debian and rpm based distributions 
- you installation instructions would be "run this script"

What are your thoughts?

**Comment by pglombardo** [comment] 2020-11-30 09:21
Hi @andrew-klassen - I'm not sure how I missed this post and generous offer.  This is really a larger problem that exists with all such applications based on Ruby on Rails.  The most popular solution these days [seem to be containers](https://hub.docker.com/u/pglombardo).

I'd be more than happy to merge an Ansible script that does what you outlined as long as we maintain choice because then there is another subset of users who don't know how to install and use Ansible.  So there are no 100% solutions unfortunately.

Are there any remaining items on this issue that I can help out with or shall we close it out?

**Comment by avielc** [comment] 2020-12-14 10:17
@pglombardo - Hey mate! 
Yea, I would really love the ability to change the ports to something random + add https to it. 
I'm using the Docker solution, and having some trouble locating the files (not too advanced on the docker area) 
if you could guide me to the right config location it'll be really helpful!
(using Centos + docker)

Thank you!

**Comment by pglombardo** [comment] 2020-12-14 15:21
Hi @avielc - you could do a simple port remap from docker with `docker run -p "81:5000" pglombardo/pwpush-ephemeral:latest`

That would then allow requests to `localhost:81` to get rerouted to the running container on docker internal port 5000.

With this, you could setup an nginx proxy with an SSL cert and setup the docker container as the backend component for nginx.

If you need it, here are the important bits related to containers in this repo:

Containerization directory holds everything:
https://github.com/pglombardo/PasswordPusher/tree/master/containerization

The default port that a container uses is specified in the Dockerfile:
https://github.com/pglombardo/PasswordPusher/blob/master/containerization/pwpush-ephemeral/Dockerfile#L19

You could modify that file as needed and rebuild the container with `docker build --no-cache -t my-pwpush-container:latest .` and `docker run -p "81:5001" my-pwpush-container:latest`

Side note that the pwpush-postgres container has a bug right now that needs fixing soon in #163

**Comment by avielc** [comment] 2020-12-14 17:06
Thanks for the info @pglombardo ! This is epic! 
I'll be using that then :)

**Comment by avielc** [comment] 2020-12-16 10:55
Hey @pglombardo  - sorry to bother you about it again (apparently I'm still missing something here)
What I've done:
I changed the private.rb (the env that is referred to in the Dockerfile you mentioned) with the addition command "config.force_ssl = true" 
yet, I get an error of "too many redirects" on the apache I setup. 

the issue I'm facing. 
I want the container to be redirected to https using Apache, (externally installed on the machine) 

any ideas what i'm missing? 
Thanks

**Comment by andrew-klassen** [comment] 2020-12-24 02:58
@avielc  if the site is working with http on port 5000 then the issue is with your apache configuration. Your httpd server should be serving https on port 443 but pwpusher should be listening http on port 5000. You shouldn't have to mess with the pwpusher config if you go the reverse proxy route.

Most engineers I know use nginx for reverse proxies because its more lightweight. But its definitely achievable with apache. I would post a censored out version of your httpd config and the /var/log/httpd/error_log. Then, someone can provide you with more specified help. If you have not done so already, compare your config to working examples of an httpd reverse proxy online.

**Comment by avielc** [comment] 2020-12-30 10:20
Sorry it took me so long to reply back @andrew-klassen - and thanks for replying!
I actually worked on the matter with the team, and we did go into the pwpusher, as the apache configuration were correct. 
and we couldn't figure what is wrong. 
in short, 
take the first screenshot provided in this issue (the box shows "http://......" instead of "https..." (which appears correctly in the web address. )

the current workaround is simply copying the web address instead of the text inside box that appears. (aka screenshot up top) 
since this works I've dropped priority on figuring it out, as it is just bothering more than actually not working. 
(copy pasting the link from the web address works as intended. it's just the text box that doesn't want to give you the right link) 

so Thanks for now! this is a great tool and we are already using it plenty! :) 👍

**Comment by joshltek** [comment] 2020-12-30 16:34
I just saw the Craig McLaren 's post and I was wonder the same as the comments in his post about setting up SSL 443 traffic for Azure ?

**Comment by pglombardo** [comment] 2021-02-14 23:05
> Side note that the pwpush-postgres container has a bug right now that needs fixing soon in #163
FYI all that this has been fixed

> the current workaround is simply copying the web address instead of the text inside box that appears. (aka screenshot up top) since this works I've dropped priority on figuring it out, as it is just bothering more than actually not working.

Ugh - really sorry about that @avielc .  That's not ideal...

I'm testing a fix for this scenario here:
https://github.com/pglombardo/PasswordPusher/pull/166

The complexity is that `config.force_ssl=true` does more than just modify URLs.  Sometimes people need only that or in your case, only SSL URLs.  I'll see if I can find the sweet spot that fixes this for the most people but doesn't break any others.

**Comment by avielc** [comment] 2021-02-14 23:34
Thanks a lot man! I really appreciate it.
the workaround is doing its thing for me for now, but if that can be fixed
without causing you too much trouble, I'd really love to see it fly

Thanks again!

**Comment by pglombardo** [comment] 2021-02-14 23:40
@joshltek I posted a comment on Craig's blog but I think it needs to get approved...  but tldr it's doable but requires a bit of work.  Here's what I posted there:

> SSL is complex because SSL certificates for your URL have to be set up.
> 
> Up to this point, users have generally set up their own nginx SSL termination point with their own SSL certificates and then just used PasswordPusher as a backend.
> 
> I've been through the pain of setting up and managing SSL certificates too many times so these days, I just let cloud providers like Heroku manage all of that and just push application code.
> 
> If you have any suggestions or other ideas on how to make this easier, please let me know.

I'd love to figure out a fix so that we never get another SSL setup issue but I don't see a way currently.   Look at this thread as an example: Salstack, Azure, Heroku, Nginx 😂    Every environment has it's own quirky requirements.

Still, I may be able to figure out something.  Maybe Let's Encrypt has an API and I could automate the process at least for a subset of users...  I haven't checked this yet but I will.

**Comment by thefirstben** [comment] 2021-11-03 16:53
Hello, thanks for the app, yes the env variable FORCE_SSL works as expected.

**Comment by pglombardo** [comment] 2021-11-04 08:33
I'll close this issue unless something remains.

FORCE_SSL works and #166 is merged.  Setting up a SSL termination point is always a bit complex when done manually.  We now have a [K8s setup with SSL](https://github.com/pglombardo/PasswordPusher/tree/master/containers/kubernetes) too.

**Closed** 2021-11-05 14:14 UTC
Labels: feature request, documentation, question
