### ISSUE TITLE
assets compilation issue

### ISSUE THREAD

**Issue by abrechon** [pglombardo/PasswordPusher#41] opened 2016-08-16 10:02 UTC
Hi there, 

first of all thanks for this great app. i get an error in assets compilation in production env and css more precisely.

Here is the output of bundle exec rake assets:precompile from log/production.log

``` 
Compiled users.css  (2ms)  (pid 48421)
Compiled application.css  (40ms)  (pid 48421)
Compiled jquery.js  (3ms)  (pid 48421)
Compiled jquery_ujs.js  (0ms)  (pid 48421)
Compiled api.js  (33ms)  (pid 48421)
Compiled errors.js  (1ms)  (pid 48421)
Compiled fd-slider.js  (1ms)  (pid 48421)
Compiled jquery-cookie.js  (0ms)  (pid 48421)
Compiled jquery.noty.js  (0ms)  (pid 48421)
Compiled layouts/top.js  (0ms)  (pid 48421)
Compiled passwords.js  (0ms)  (pid 48421)
Compiled spoiler.js  (0ms)  (pid 48421)
Compiled themes/default.js  (0ms)  (pid 48421)
Compiled modernizr.js  (0ms)  (pid 48421)
Compiled application.js  (78ms)  (pid 48421)
Warning. Error encountered while saving cache /Users/xx/xx-xx/xx-xx-xx/tmp/cache/sass/efcd6618511989f0583e175ca710234f909d501b/api.css.scssc: can't dump anonymous class #<Class:0x007f829b4b4c48>

Compiled api.css  (2ms)  (pid 48421)
Warning. Error encountered while saving cache /Users/xx/xx-xx/xx-xx-xx/tmp/cache/sass/efcd6618511989f0583e175ca710234f909d501b/errors.css.scssc: can't dump anonymous class #<Class:0x007f829b4b4c48>

Compiled errors.css  (1ms)  (pid 48421)
Compiled fd-slider.css  (1ms)  (pid 48421)
Warning. Error encountered while saving cache /Users/xx/xx-xx/xx-xx-xx/tmp/cache/sass/efcd6618511989f0583e175ca710234f909d501b/global.css.scssc: can't dump anonymous class #<Class:0x007f829b4b4c48>

Compiled global.css  (9ms)  (pid 48421)
Warning. Error encountered while saving cache /Users/xx/xx-xx/xx-xx-xx/tmp/cache/sass/efcd6618511989f0583e175ca710234f909d501b/passwords.css.scssc: can't dump anonymous class #<Class:0x007f829b4b4c48>

Compiled passwords.css  (14ms)  (pid 48421)
Warning. Error encountered while saving cache /Users/xx/xx-xx/xx-xx-xx/tmp/cache/sass/efcd6618511989f0583e175ca710234f909d501b/users.css.scssc: can't dump anonymous class #<Class:0x007f829b4b4c48>

Compiled users.css  (3ms)  (pid 48421)
Compiled application.css  (51ms)  (pid 48421)
 ```

sass is 3.4.22, any ideas ? 

Thanks !

**Comment by abrechon** [comment] 2016-08-16 12:52
i finally fixed it using 

```
gem 'rails', '3.2.21'

group :assets do
  gem 'sass', '~> 3.1.10'
  gem 'sass-rails',   '~> 3.2.6'
```

but still app is not serving css and images

```
14:47:35 web.1  | I, [2016-08-16T14:47:35.470928 #71587]  INFO -- : listening on addr=0.0.0.0:5000 fd=12
14:47:35 web.1  | I, [2016-08-16T14:47:35.476305 #71587]  INFO -- : master process ready
14:47:35 web.1  | I, [2016-08-16T14:47:35.481456 #71595]  INFO -- : worker=1 ready
14:47:35 web.1  | I, [2016-08-16T14:47:35.481488 #71594]  INFO -- : worker=0 ready
14:47:35 web.1  | I, [2016-08-16T14:47:35.482163 #71596]  INFO -- : worker=2 ready
14:47:43 web.1  | 127.0.0.1 - - [16/Aug/2016 14:47:43] "GET / HTTP/1.1" 304 - 2.2861
14:47:44 web.1  | 127.0.0.1 - - [16/Aug/2016 14:47:44] "GET /assets/application-52a9cd36f28bae5123a49d180aeb31f3.css HTTP/1.1" 500 - 0.1651
14:47:45 web.1  | 127.0.0.1 - - [16/Aug/2016 14:47:45] "GET /assets/forkme-02dcd927ee9c244e1c1f839e477aa118.png HTTP/1.1" 500 - 1.7888
14:47:45 web.1  | 127.0.0.1 - - [16/Aug/2016 14:47:45] "GET /assets/application-290fe1f424293e8c8bd4a7c5a3e5b33d.js HTTP/1.1" 304 - 1.6387
14:47:46 web.1  | 127.0.0.1 - - [16/Aug/2016 14:47:46] "GET /assets/favicon-8c20eb6b69a5cdabe3ee0e8bbc00c60b.ico HTTP/1.1" 304 - 0.1696
```

if i ls the assets folder in app i don't see the requested files.

😢

**Comment by pglombardo** [comment] 2016-08-16 20:43
Ugh @abrechon this seems to be a recurring issue lately.  I really need to figure out what the problem is and why the inconsistency between users.  Sorry for the issue!

For the last bit, make sure that you have `config.serve_static_assets = true` set in your environment file.  If you set `RAILS_ENV=private`, then the line is here:
https://github.com/pglombardo/PasswordPusher/blob/master/config/environments/private.rb#L12

That _should_ resolve the static assets not being served.

Either way, I'll look into this a bit more soon and post back here.

Best,
Peter

**Comment by abrechon** [comment] 2016-08-17 07:54
well, if i set RAILS_ENV=private everything's working fine, if move to RAILS_ENV=production then assets are not being served. I did export ENV and assets precompile after moving to production. So for now i'll stick to private, i don't see any major difference between private or production.

Thanks !

**Comment by pglombardo** [comment] 2016-09-07 15:31
If there are any other issues, please let me know @abrechon !  Thanks.  Closing this issue for now.

**Closed by pglombardo** 2016-09-07 15:31 UTC

**Comment by pglombardo** [comment] 2023-02-13 22:04
I tripped across this issue and couldn't help but post.  The whole process is much smoother now with pre-compilation done at container build time.  Give it a shot:

`docker run -d -p "5100:5100" pglombardo/pwpush-ephemeral`

I hope all is well.
